(function () {
  window.DB_BUILD_DATA = {
    re: {
      axisLabels: ["Сложность", "DPS", "Мобильность", "Восстановление", "Скорость"],
      invert: [false, false, false, false, false],
      defaultPair: [0, 2],
      builds: [
        {
          id: "333-ceiling",
             description: "{turningslash} откатывает умение {fatalwave}.",
          name: "333 Шакрамы",
          accent: "#e56c7e",
          pentagon: [8, 9, 5, 8.5, 8.5],
          difficulty: 8,
          trixion: 1.2,
          trixionConfirmed: true,
          playstyle: "Сброс скилов",
          bestFor: "\u2728 Всесторонний потолок урона",
          recommended: true,
          compareEnabled: true,
        },
        {
          id: "313-high-floor",
             description: "{surge} откатывает умение {fatalwave}.",
          name: "313 Шакрамы 2.0",
          accent: "#e6b422",
          pentagon: [7.5, 8, 5, 9, 10],
          difficulty: 7.5,
          trixion: 1.17,
          trixionConfirmed: true,
          playstyle: "Быстро и комфортно",
          bestFor: "\uD83D\uDC9C Комфорт и восстановление",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "111-head-hunt",
             description: "Классический билд без {fatalwave:Воздушных шакрам}, с {deathsentence:Смертным приговором}.",
          name: "111 Классика",
          accent: "#59c08f",
          pentagon: [9, 8, 5, 7, 10],
          difficulty: 9,
          trixion: 1.18,
          trixionConfirmed: true,
          playstyle: "Быстро и карательно",
          bestFor: "\uD83D\uDD2A Раскрытие скилов и оглушение",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "standard",
             description: "Билд без использования ядер, с {spincutter:Разрубающими лезвиями}.",
          name: "Стандарт без ядер",
          accent: "#8d8b93",
          pentagon: [6, 6, 8.5, 4, 6],
          difficulty: 6,
          trixion: null,
          trixionConfirmed: true,
          playstyle: "Симулятор AFK",
          bestFor: "\uD83C\uDF31 Билд для новичка до А.Р.К.",
          recommended: false,
          compareEnabled: true,
        },
      ],
    },
    surge: {
      axisLabels: ["Сложность", "DPS", "Мобильность", "Экспозиция", "Скорость"],
      invert: [false, false, false, true, false],
      defaultPair: [0, 1],
      axisNoteIndex: 3,
      axisNote: "Экспозиция: риск атак в спину и позиционный риск.",
      builds: [
        {
          id: "111-classic",
             description: "Классичный геймплей Твёрдой воли.",
          name: "111 Классика",
          accent: "#e56c7e",
          pentagon: [7.5, 9, 7, 6.5, 7],
          difficulty: 7.5,
          trixion: 1.23,
          trixionConfirmed: true,
          playstyle: "Комбо-вспышка",
          bestFor: "\uD83E\uDD81 Классичный геймплей Твёрдой воли",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "222-speedy",
             description: "Видоизменённый 111 — ощущается быстрее.",
          name: "222 Ускоренный",
          accent: "#59c08f",
          pentagon: [7, 9, 9, 8, 8],
          difficulty: 7,
          trixion: 1.25,
          trixionConfirmed: true,
          playstyle: "Максимальная мобильность",
          bestFor: "\uD83D\uDC06 Простое удержание урона",
          recommended: false,
          compareEnabled: true,
        },
        {
          id: "333-blitz",
             description: "Билд через {blitzrush:Охоту за головами}.",
          name: "333 Охота за головами",
          accent: "#a8a2b2",
          pentagon: [8, 8, 8, 9, 6],
          difficulty: 8,
          trixion: 1.2,
          trixionConfirmed: false,
          playstyle: "Сброс скилов",
          bestFor: "\uD83D\uDC2F Ожидание баффов",
          recommended: false,
          compareEnabled: true,
        },
      ],
    },
  };
})();
