(function () {
  window.DB_SKILL_NAMES = {
    voidstrike: "Искусство меча",
    twinshadows: "Двойная плеть",
    soulabsorber: "Длань Авесты",
    deathsentence: "Смертный приговор",
    fatalwave: "Воздушные шакрамы",
    windcut: "Неумолимое притяжение",
    deathtrance: "Боевой транс",
    surpriseattack: "Внезапный выпад",
    breakingmoon: "Неуловимый пируэт",
    bladedance: "Блиц",
    darkaxel: "Аксель",
    upperslash: "Восходящий вихрь",
    fallstar: "Полярная звезда",
    maelstrom: "Плащ клинков",
    turningslash: "Иссечение",
    deathlyslash: "Убийственная сталь",
    surge: "Концентрация воли",
    bladeassault: "Призрачные клинки",
    flashblink: "Сверхновая",
    blitzrush: "Охота за головами",
    earthcleaver: "Двуручный хват",
    headhunt: "Хитроумный финт",
    spincutter: "Разрубающие лезвия",
    atropine: "Ардопин-Х",
    stimulant: "Мощная «Эйфория»",
    striploin: "Филейный стейк с грибами",
    steak: "Сливочный отборный кролик",
    fish: "Томатная фаршированная рыба",
    azena: "Благословение Азены",
    feast: "Ивентовая еда",
    vernesewine: "Бирнийское вино",
    ealynsblessing: "Шато де Розе",
    grudge: "Титаноборец",
    ambushmaster: "Бесшумный убийца",
    raidcaptain: "Неутомимый натиск",
    adrenaline: "Адреналин",
    keenbluntweapon: "Моргенштерн",
    curseddoll: "Голем",
    massincrease: "Карающая длань",
    maxmp: "Источник маны",
    spiritabsorption: "Стремительность",
    bleed: "Bleed",
  };
})();
